stages:
  - build
  - test

image: node:20

cache:
  paths:
    - friendship-service/node_modules/

before_script:
  - echo "Starting CI Pipeline..."
  - node -v
  - npm -v

build:
  stage: build
  script:
    - cd friendship-service && npm ci
  only:
    - merge_requests
    - vim

unit_tests:
  stage: test
  script:
    - cd friendship-service && npm test --detectOpenHandles
  only:
    - merge_requests
    - vim