# ======================================================
# DESCRIPTION
# ======================================================
# Compose file defining application services in development/testing environments.
#
# Attention: for other backend application definitions such as databases, messaging brokers, ...
# please consult corresponding directories (./databases, ./infra, ...).

services:
  activity-recommendation-system:
    build:
      context: ./services/activity-recommendation-system
      target: builder
    container_name: activity-recommendation-system

    env_file:
      - .env.dev
    volumes:
      - ./services/activity-recommendation-system:/application-recommendation-system
    ports:
      - ${ACTIVITY_RECOMMENDATION_SYSTEM_PORT}:${ACTIVITY_RECOMMENDATION_SYSTEM_PORT}
    environment:
      PORT: ${ACTIVITY_RECOMMENDATION_SYSTEM_PORT}
      MAIN_DB_USER: ${MAIN_DB_USER}
      MAIN_DB_PASS: ${MAIN_DB_PASS}
      MAIN_DB_NAME: ${MAIN_DB_NAME}
      MAIN_DB_HOST: ${MAIN_DB_HOST}
      MAIN_DB_PORT: ${MAIN_DB_PORT}
      SUDO_API_KEY: ${SUDO_API_KEY}
      USES_SSL: ${USES_SSL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      PLACES_PHOTO_CLEANUP_ENABLED: ${PLACES_PHOTO_CLEANUP_ENABLED}
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
      GCS_BUCKET_PLACES_PHOTOS_NAME: ${GCS_BUCKET_PLACES_PHOTOS_NAME}
      PLACES_PHOTOS_GALLERY_BASE_URL: ${PLACES_PHOTOS_GALLERY_BASE_URL}
      PLACES_PHOTOS_UPLOAD_SERVER: ${PLACES_PHOTOS_UPLOAD_SERVER}
      MATCHING_SESSIONS_SERVICE_IDENTIFIER: ${MATCHING_SESSIONS_SERVICE_IDENTIFIER}

  matching-sessions-service:
    build:
      context: ./services/matching-sessions-service
      target: builder
    container_name: matching-sessions-service
    command: npm run dev
    env_file:
      - .env.dev
    volumes:
      - ./services/matching-sessions-service:/usr/src/app
      - ./services/matching-sessions-service/src/config/credentials/firebase.json:/usr/src/app/config/credentials/firebase.json
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - ${MATCHING_SESSIONS_SERVICE_API_PORT}:${MATCHING_SESSIONS_SERVICE_API_PORT}
    environment:
      MATCHING_SESSIONS_SERVICE_IDENTIFIER: ${MATCHING_SESSIONS_SERVICE_IDENTIFIER}
      PORT: ${MATCHING_SESSIONS_SERVICE_API_PORT}
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASS}
      POSTGRES_DB: ${MAIN_DB_NAME}
      POSTGRES_HOST: db1
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      RABBITMQ_AMQP_PORT: ${RABBITMQ_AMQP_PORT}
      RABBITMQ_USER: "root"
      RABBITMQ_PASS: "toor"
      FIREBASE_APPLICATION_CREDENTIALS: ${FIREBASE_APPLICATION_CREDENTIALS}
      RECOMMENDATION_SYSTEM_PORT: ${ACTIVITY_RECOMMENDATION_SYSTEM_PORT}
      RECOMMENDATION_SERVICE_HOST: ${RECOMMENDATION_SERVICE_HOST}
      MAIN_DB_MAX_CONNECTIONS: ${MAIN_DB_MAX_CONNECTIONS}
      POSTGRES_POOL_MAX: ${POSTGRES_POOL_MAX}
      ACTIVITY_RECOMMENDATION_SYSTEM_API_BASE_URL: ${ACTIVITY_RECOMMENDATION_SYSTEM_API_BASE_URL}
      MAIN_DB_HOST: ${MAIN_DB_HOST}
      USES_SSL: ${USES_SSL}
      IS_DEV: ${IS_DEV}
      RECSYS_TOKEN: ${RECSYS_MESSAGING_SERVICE_TOKEN}
      SKIP_INTERNAL_AUTH: ${SKIP_INTERNAL_AUTH}
      SUDO_API_KEY: ${SUDO_API_KEY}
      APP_CLIENT_UUID: ${APP_CLIENT_UUID}

  user-account-service:
    build:
      context: ./services/user-account-service
      target: builder
    container_name: user-account-service
    command: npm run dev
    env_file:
      - .env.dev
    volumes:
      - ./services/user-account-service:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - ${USER_ACCOUNT_SERVICE_API_PORT}:${USER_ACCOUNT_SERVICE_API_PORT}
    environment:
      PORT: ${USER_ACCOUNT_SERVICE_API_PORT}
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASS}
      POSTGRES_DB: ${MAIN_DB_NAME}
      POSTGRES_HOST: ${MAIN_DB_HOST}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      IDENTIFIER: ${USER_ACCOUNT_SERVICE_IDENTIFIER}
      RECOMMENDATION_SYSTEM_PORT: ${ACTIVITY_RECOMMENDATION_SYSTEM_PORT}
      VERIFICATION_MAIL_DATA_KEY: ${VERIFICATION_MAIL_DATA_KEY}
      HOSTING_DOMAIN_NAME: ${USER_ACCOUNT_SERVICE_HOST}
      USES_SSL: ${USES_SSL}
      IS_DEV: ${IS_DEV}
      BYPASS_EMAIL_VERIFICATION: ${BYPASS_EMAIL_VERIFICATION}
      USER_THUMBNAIL_ENCRIPTION_KEY: ${USER_THUMBNAIL_ENCRIPTION_KEY}
      GALLERY_BASE_URL: ${GALLERY_BASE_URL}
      SUDO_API_KEY: ${SUDO_API_KEY}
      EMAIL_API_ENDPOINT: ${EMAIL_API_ENDPOINT}
      EMAIL_MAILERSEND_API_KEY: ${EMAIL_MAILERSEND_API_KEY}
      IMAGE_UPLOAD_SERVER: ${IMAGE_UPLOAD_SERVER}
      EMAIL_MAILGUN_API_KEY: ${EMAIL_MAILGUN_API_KEY}
      MAIN_DB_MAX_CONNECTIONS: ${MAIN_DB_MAX_CONNECTIONS}
      POSTGRES_POOL_MAX: ${POSTGRES_POOL_MAX}
      MINIMAL_PASSWORD_STRENGTH_LVL: ${MINIMAL_PASSWORD_STRENGTH_LVL}

  friendship-service:
    build:
      context: ./services/friendship-service
      target: builder
    container_name: friendship-service
    command: npm run dev
    env_file:
      - .env.dev
    volumes:
      - ./services/friendship-service:/usr/src/app
      - ./services/friendship-service/config/credentials/firebase.json:/usr/src/app/config/credentials/firebase.json
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - ${FRIENDSHIP_SERVICE_API_PORT}:${FRIENDSHIP_SERVICE_API_PORT}
    environment:
      PORT: ${FRIENDSHIP_SERVICE_API_PORT}
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASS}
      POSTGRES_DB: ${MAIN_DB_NAME}
      POSTGRES_HOST: ${MAIN_DB_HOST}
      MAIN_DB_MAX_CONNECTIONS: ${MAIN_DB_MAX_CONNECTIONS}
      POSTGRES_POOL_MAX: ${POSTGRES_POOL_MAX}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      USES_SSL: ${USES_SSL}
      IS_DEV: ${IS_DEV}
      FIREBASE_APPLICATION_CREDENTIALS: ${FIREBASE_APPLICATION_CREDENTIALS}
      SUDO_API_KEY: ${SUDO_API_KEY}
