

export enum ErrorCodes {

    // general
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",

    // Auth
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",

    // Session
    SESSION_CREATION_FAILED = "SESSION_CREATION_FAILED",
    CONNECTION_TO_SESSION_FAILED = "CONNECTION_TO_SESSION_FAILED",
    CHECKING_SESSION_STATE_FAILED = "CHECKING_SESSION_STATE_FAILED",
    SESSION_INIT_DATA_UPDATE_FAILED = "SESSION_INIT_DATA_UPDATE_FAILED",
    SESSION_TERMINATION_FAILED = "SESSION_TERMINATION_FAILED",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
    SESSION_START_FAILED = "SESSION_START_FAILED",

    // Chat
    FETCHING_MESSAGES_FAILED = "FETCHING_MESSAGES_FAILED",

    USERS_AVAILABILITY_CHECK_FAILED = "USER_AVAILABILITY_CHECK_FAILED",
    GROUP_META_INITIALIZATION_FAILED = "GROUP_META_INITIALIZATION_FAILED",

}