
export enum ErrorCodes {

    // general
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",

    // Auth
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",

    USER_NOT_FOUND = "USER_NOT_FOUND",
}